### PR TITLE
Add smoothing term based on change in slope (second derivative)

### PR DESCRIPTION
**Pull request by uvafan**
In addition to first derivative, to avoid notches. More info at https://docs.google.com/document/d/1sawgEzYF-xrCk8Lnc3PIZde_Jg6VQ4R1-kK5hKvtgdo/edit#heading=h.rhxxklbrss0w. Analysis of effects at https://docs.google.com/document/d/1sawgEzYF-xrCk8Lnc3PIZde_Jg6VQ4R1-kK5hKvtgdo/edit#heading=h.pyyxu7uwlefu

TODO: move term weights to constants area/file, perhaps keep division by `dist.normed_log_densities.size` and scale term weights accordingly.

[Companion Elicit PR](https://github.com/oughtinc/elicit/pull/358)

### CODE REVIEW

**Comment by brachbach** [comment]
@uvafan does it make sense to go ahead and close this now? Or are you still working on it?

**Comment by uvafan** [comment]
@brachbach yes these can be closed for now, pending confirmation from @stuhlmueller that he isn't still thinking about how to speed it up

**Comment by stuhlmueller** [comment]
I still want to think about it but I can re-open if I have ideas.

**Comment by brachbach** [comment]
Closed because we couldn't make it fast enough

**Pull request closed without merging**
