### PR TITLE
Some copy edits on the decision-relevant question

### PR DESCRIPTION
**Pull request by steveryb**
Made some things clearer, added some links, and defined metaculus.

### CODE REVIEW

**Comment by brachbach** [comment]
@steveryb FYI I'm working on a new version of this notebook on this PR: https://github.com/oughtinc/ergo/pull/268

I'll plan to merge your commits into the branch for that PR when I get a chance!

**Comment by steveryb** [comment]
Oh great! It probably makes sense that I don't then put more effort into editing this one for now - @brachbach I'll use you merging this request into that as an indication that I should reread. In the meantime, ping me if you want an extra set of eyes on #268 :)

**Comment by brachbach** [comment]
Sounds good!

Thanks @steveryb!

**Comment by brachbach** [comment]
@steveryb I've incorporated your changes, so I'm closing this branch.

I'll let you know when #268 is done so that you can check it out and see whether you have any suggestions! :)

**Comment by steveryb** [comment]
Thanks Ben!

**Pull request closed without merging**
