### PR TITLE
Fix quickstart

### PR DESCRIPTION
**Pull request by zmpster**
Closes https://github.com/oughtinc/ergo/issues/424

I'm not sure what best practices are for putting Notebooks up in a PR are, so let me know if I should do anything else here.

### CODE REVIEW

**Comment by stuhlmueller** [comment]
Also updated the [scrubbed](https://github.com/oughtinc/ergo/tree/master/notebooks/scrubbed) notebook ([instructions](https://ergo.ought.org/en/latest/nbs_contrib.html))?

**Comment by zmpster** [comment]
@stuhlmueller Done!

**Review by brachbach — APPROVED** [review]
I followed the instructions and tried the notebooks, LGTM!

**Comment by zmpster** [comment]
@brachbach I'm still stuck on testing/merging this one, so I think you'll have to make your own PR on the original repo if/when you want to merge.

**Comment by brachbach** [comment]
Thanks for reminding me @zmpster 

We don't test the notebooks, so no use in testing this.

@stuhlmueller approve and we can merge?

**Review by stuhlmueller — APPROVED** [review]

**Pull request merged**
