### PR TITLE
Make ergo package installable

### PR DESCRIPTION
**Pull request by seanjtaylor**
I had trouble install the ergo package. These changes did the trick.

### CODE REVIEW

**Comment by seanjtaylor** [comment]
The package versions are actually impossible to resolve at the moment.

- Latest Numpyro (0.2.4) version requires `jax==0.1.57` and `jaxlib==0.1.37`
- `ergo` uses a jax feature that does not appear to be available in `0.1.57` (see stack trace below)

```
>>> import ergo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Users/seant/src/ergo-sjt/ergo-test2/lib/python3.7/site-packages/ergo-0.8.3-py3.7.egg/ergo/__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Users/seant/src/ergo-sjt/ergo-test2/lib/python3.7/site-packages/ergo-0.8.3-py3.7.egg/ergo/distributions/__init__.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Users/seant/src/ergo-sjt/ergo-test2/lib/python3.7/site-packages/ergo-0.8.3-py3.7.egg/ergo/distributions/location_scale_family.py", line 25, in <module>
  File "/Users/seant/src/ergo-sjt/ergo-test2/lib/python3.7/site-packages/ergo-0.8.3-py3.7.egg/ergo/distributions/location_scale_family.py", line 31, in LSDistribution
AttributeError: module 'jax.scipy.stats' has no attribute 'logistic'
```

**Comment by stuhlmueller** [comment]
Thanks Sean!

I've been installing Ergo as follows, using a virtualenv with Python 3.6.9:

```
pip install poetry # https://github.com/python-poetry/poetry/issues/532
pip install git+https://github.com/oughtinc/ergo.git
```

This works on Colab (e.g. [here](https://github.com/oughtinc/ergo/blob/master/notebooks/el-paso-workflow.ipynb)). Does this not work for you, or is it different from what you'd want?

In general we're using the Poetry package manager. To generate a requirements.txt, you could install it and try its [export command](https://python-poetry.org/docs/cli/#export).

**Comment by stuhlmueller** [comment]
> Latest Numpyro (0.2.4) version requires jax==0.1.57 and jaxlib==0.1.37

We're using a dev version of Numpyro. (Specified in [pyproject.toml](https://github.com/oughtinc/ergo/blob/master/pyproject.toml#L22).)

**Comment by seanjtaylor** [comment]
I don't really use colab, was hoping to install on my local machine. I haven't heard of poetry, but it had trouble generating `requirements.txt` that parsed for me (with a fresh virtual environment). 

Running `poetry install` was able to install the package for me so I can use that method for now. I can just close out this PR since I don't know how to resolve this problem.

**Comment by stuhlmueller** [comment]
I added [installation instructions](https://github.com/oughtinc/ergo#local-installation) to the readme. This just explains how to use Poetry. Over time we'll switch to a more standard install from PyPI.

**Pull request closed without merging**
